#! /usr/bin/env bash
pipeline=${1:-StableDiffusionPipeline}
fixture_dir=${2:-"test/pipelines/$pipeline"}
outputs_dir=${3:-"test/outputs"}
mkdir -p $outputs_dir

for file in $fixture_dir/*.json; do
    body=$(cat $file)
    name=$(basename $file .json)
    

    result=$(curl -X POST \
        'http://localhost:1234/generate' \
        --header 'Content-Type: application/json' \
        --data-raw "$body" \
        --fail 2>/dev/null
        )
    exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        echo "----------------------"
        echo "Failed to generate $pipeline/$name.json"
        echo $body | jq
        echo "----------------------"
        continue
    fi
    meta=$(echo $result | jq -r '.meta')
    echo $meta | jq
    for idx in $(echo $result | jq -r '.images | keys | .[]'); do
        filename=$outputs_dir/$pipeline-$name-$(($idx + 1)).png
        image=$(echo $result | jq -r ".images[$idx]")
        echo $image | base64 -d > $filename
    done
done