version: '3'

services:
  igi:
    image: saladtechnologies/image-generation-inference:latest
    ports:
      - 1234:1234
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
