version: '3'

services:
  igi:
    image: saladtechnologies/image-generation-inference:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      #   CIVITAI_MODEL_VERSION_IDS: 8815
      # LAUNCH_CHECKPOINT: stickerArt_sticker.safetensors
      # LAUNCH_VAE: sd2-1
      VAE_URLS: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/diffusion_pytorch_model.fp16.safetensors?download=true,https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/vae/config.json?download=true
      # LOAD_SAFETY_CHECKER: true
