version: '3'

services:
  igi:
    image: saladtechnologies/image-generation-inference:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      LOG_LEVEL: info
      # These are the models assumed by the test suite
      CIVITAI_MODEL_VERSION_IDS: 122143,128713,8815,131579
      # COMPILE_MODEL: false
