#! /usr/bin/env bash

curl  -X POST \
  'http://localhost:1234/generate' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "checkpoint": "dreamshaperXL_turboDpmppSDE.safetensors",
  "pipeline": "StableDiffusionXLPipeline",
  "a1111_scheduler": "DPM++ SDE Karras",
  "parameters": {
    "prompt": "a cat",
    "num_inference_steps": 4,
    "guidance_scale": 2.0
  }
}' | jq -r '.images[0]' | base64 -d > cat.png