#! /usr/bin/env bash

curl  -X POST \
  'http://localhost:1234/generate' \
  --header 'Accept: */*' \
  --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "checkpoint": "dreamshaper_8.safetensors",
  "pipeline": "StableDiffusionPipeline",
  "a1111_scheduler": "Euler a",
  "parameters": {
    "prompt": "a cat",
    "num_inference_steps": 15
  }
}' | jq -r '.images[0]' | base64 -d > cat.png